version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - "> 1.19.5"
  - dependency-name: hypothesis
    versions:
    - 6.2.0
    - 6.3.0
    - 6.3.4
    - 6.6.0
    - 6.8.1
    - 6.8.3
    - 6.8.4
    - 6.9.0
  - dependency-name: pylint
    versions:
    - 2.7.2
    - 2.7.4
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: isort
    versions:
    - 5.7.0
